name: Monorepo CI

on:
  push:
    paths:
      - 'front-end/**'
      - 'backend/**'
jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: cd front-end && npm install

      - name: Run tests
        run: cd front-end && npm test

      - name: Build front-end
        run: cd front-end && npm run build

  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run tests & Install dependencies
        run: cd backend && python -m pip install --upgrade pip && pip install -r requirements.txt

      - name: Build
        run: cd backend && python setup.py build
          
          
